# Generated by Django 4.1.7 on 2023-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobtile', models.CharField(max_length=200)),
                ('Jobtype', models.TextField(max_length=255)),
                ('CompanyName', models.TextField(max_length=20)),
                ('CompanyURL', models.TextField(max_length=200)),
                ('JobArea', models.TextField(max_length=40)),
                ('JobLink', models.TextField(max_length=200)),
                ('JobDescription', models.TextField(max_length=200)),
                ('Skill', models.TextField(max_length=200)),
            ],
        ),
    ]
