# Generated by Django 4.1.7 on 2023-03-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jobmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobmodel',
            table=None,
        ),
    ]
