# Generated by Django 4.1.7 on 2023-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_jobmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Message', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='Jobtile',
            new_name='Jobtitle',
        ),
    ]
