# Generated by Django 4.1.7 on 2023-03-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmodel_rename_jobtile_jobmodel_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='Subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
