# Generated by Django 4.1.7 on 2023-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmodel_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InternTitle', models.CharField(max_length=100)),
                ('InternType', models.TextField(max_length=50)),
                ('CompanyName', models.TextField(max_length=50)),
                ('CompanyURL', models.TextField(max_length=200)),
                ('InternArea', models.TextField(max_length=40)),
                ('InternLink', models.TextField(max_length=100)),
                ('InternDescription', models.TextField(max_length=200)),
                ('Skill', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=40)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
